In [4]:
!pip install gensim

   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   --- ------------------------------------ 2.1/24.4 MB 28.6 MB/s eta 0:00:01
   --- ------------------------------------ 2.4/24.4 MB 5.9 MB/s eta 0:00:04
   -------- ------------------------------- 5.2/24.4 MB 11.2 MB/s eta 0:00:02
   ---------- ----------------------------- 6.3/24.4 MB 8.5 MB/s eta 0:00:03
   ------------ --------------------------- 7.3/24.4 MB 7.8 MB/s eta 0:00:03
   -------------- ------------------------- 8.7/24.4 MB 7.3 MB/s eta 0:00:03
   --------------- ------------------------ 9.4/24.4 MB 6.8 MB/s eta 0:00:03
   ----------------- ---------------------- 10.7/24.4 MB 6.7 MB/s eta 0:00:03
   ------------------ --------------------- 11.5/24.4 MB 6.4 MB/s eta 0:00:03
   ------------------- -------------------- 12.1/24.4 MB 6.2 MB/s eta 0:00:02
   -------------------- ------------------- 12.6/24.4 MB 5.7 MB/s eta 0:00:03
   --------------------- ------------------ 12.8/24.4 MB 5.5 MB/s eta 0:00:03

In [5]:
import gensim.downloader as api
model = api.load("word2vec-google-news-300")


[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [7]:
word_vectors = model

print(word_vectors['computer'])

[ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01
  5.51757812e-02  5.02929

In [8]:
print(word_vectors['cat'].shape)

(300,)


King + woman - man = ? --> the meaning is preserved

In [9]:
print(word_vectors.most_similar(positive=['king', 'woman'], negative=['man'], topn=10))

[('queen', 0.7118192911148071), ('monarch', 0.6189674735069275), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321243286133), ('kings', 0.5236844420433044), ('Queen_Consort', 0.5235945582389832), ('queens', 0.518113374710083), ('sultan', 0.5098593831062317), ('monarchy', 0.5087411999702454)]


Lets check the similarity b/w a few pair of words

In [10]:
print(word_vectors.similarity('woman', 'man'))
print(word_vectors.similarity('king', 'queen'))
print(word_vectors.similarity('uncle', 'aunt'))
print(word_vectors.similarity('boy', 'girl'))
print(word_vectors.similarity('nephew', 'niece'))
print(word_vectors.similarity('paper', 'water'))

0.76640123
0.6510957
0.76434743
0.8543272
0.7594367
0.11408083


In [11]:
print(word_vectors.most_similar("tower", topn=5))

[('towers', 0.8531749248504639), ('skyscraper', 0.6417425870895386), ('Tower', 0.639177143573761), ('spire', 0.5946877598762512), ('responded_Understood_Atlasjet', 0.5931612849235535)]


In [15]:
import numpy as np 

word1='man'
word2='woman'

word3='semiconductor'
word4='earthworm'

word5='nephew'
word6='niece'

# calculate the vector difference
vector_difference1 = model[word1] - model[word2]
vector_difference2 = model[word3] - model[word4]
vector_difference3 = model[word5] - model[word6]

#calculate the magnitude of the vector difference
magnitude_of_difference1 = np.linalg.norm(vector_difference1)
magnitude_of_difference2 = np.linalg.norm(vector_difference2)
magnitude_of_difference3 = np.linalg.norm(vector_difference3)

print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word1,word2,magnitude_of_difference1))
print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word3,word4,magnitude_of_difference2))
print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word5,word6,magnitude_of_difference3))

The magnitude of the difference between 'man' and 'woman' is 1.73
The magnitude of the difference between 'semiconductor' and 'earthworm' is 5.67
The magnitude of the difference between 'nephew' and 'niece' is 1.96


### Creating token embeddings

In [21]:
!pip install torch

In [25]:
import torch
input_ids = torch.tensor([2,3,5,1])

# let's create a small vocabulary of 6 words (inplace of 50k words in BPE)
# the embedding is of size 3

In [28]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [29]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [30]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [31]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
